In [2]:
import pandas as pd

In [3]:
students_data = {
    "Name": [
        "Rahi",
        "Elvis",
        "Andrew"
    ],
    "CGPA": [
        7.5,
        6.9,
        8.7,
    ]
}

df = pd.DataFrame(students_data)
df

     Name  CGPA
0    Rahi   7.5
1   Elvis   6.9
2  Andrew   8.7

In [4]:
s = pd.Series([i for i in range(1, 11)])
print(s, type(s))

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64 <class 'pandas.core.series.Series'>

In [5]:
s = pd.Series([23, 24, 25, 26], index=["Emmu bhai", "Rahi", "Elvis", "Andrew"])
print(s["Rahi"], s.iloc[0])
print(s.index)

24 23
Index(['Emmu bhai', 'Rahi', 'Elvis', 'Andrew'], dtype='object')

In [6]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([6, 7, 8, 9, 10])

print((s1 + s2) + 10)

s1[0] = 100
# print(s1)
changed_s1 = s1.drop(1)
print(s1, "\n",changed_s1)

0    17
1    19
2    21
3    23
4    25
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
 0    100
2      3
3      4
4      5
dtype: int64

In [7]:
info = {
    "Name": ["Rahi", "Elvis", "Andrew"],
    "Age": [22, 20, 19],
    "GPA": [7.8, 6.9, 8.1]
}

df = pd.DataFrame(info)
df

     Name  Age  GPA
0    Rahi   22  7.8
1   Elvis   20  6.9
2  Andrew   19  8.1

In [8]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [9]:
df.columns

Index(['Name', 'Age', 'GPA'], dtype='object')

In [19]:
# CSV 

data = pd.read_csv("Data-Files/employee_data.csv")
print(data, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [21]:
data.head()

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [22]:
data.tail()

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [26]:
data.sample()

   ID Name  Age Department  Salary
8   9  Ian   35         IT   75000

In [27]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [32]:
data["Name"] = data["Name"].astype(str)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [34]:
data.shape

(10, 5)

In [35]:
data.describe()

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [37]:
data.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

In [38]:
data.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [ ]:
# JSON 
data = pd.read_json("Data-Files/emp.json")
print(data, type(df))

In [42]:
data = pd.read_csv("Data-Files/globalAirQuality.csv")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18000 entries, 0 to 17999
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    18000 non-null  object
 1   country      18000 non-null  object
 2   city         18000 non-null  object
 3   latitude     18000 non-null  float64
 4   longitude    18000 non-null  float64
 5   pm25         18000 non-null  float64
 6   pm10         18000 non-null  float64
 7   no2          18000 non-null  float64
 8   so2          18000 non-null  float64
 9   o3           18000 non-null  float64
 10  co           18000 non-null  float64
 11  aqi          18000 non-null  int64
 12  temperature  18000 non-null  float64
 13  humidity     18000 non-null  float64
 14  wind_speed   18000 non-null  float64
dtypes: float64(11), int64(1), object(3)
memory usage: 2.1+ MB

In [43]:
data.head()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017

In [44]:
data.tail()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [45]:
data.sample()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
3437,2025-11-12 23:25:17.554219,BR,São Paulo,-23.55,-46.633,35.421,63.101,51.853,5.755,50.592,0.57,129,33.869,47.287,1.928

In [49]:
print(data["country"].unique(), data["country"].nunique())

['US' 'GB' 'FR' 'DE' 'ES' 'IT' 'CA' 'MX' 'BR' 'AR' 'ZA' 'EG' 'KE' 'NG'
 'AE' 'SA' 'QA' 'IN' 'JP' 'KR' 'CN' 'HK' 'SG' 'TH' 'MY' 'ID' 'AU' 'NZ'
 'RU' 'TR' 'IR' 'PK' 'PH' 'VN' 'PL' 'SE' 'FI' 'CH'] 38

In [50]:
print(data["city"].unique(), data["city"].nunique())

['New York' 'Los Angeles' 'London' 'Paris' 'Berlin' 'Madrid' 'Rome'
 'Toronto' 'Mexico City' 'São Paulo' 'Buenos Aires' 'Cape Town' 'Cairo'
 'Nairobi' 'Lagos' 'Dubai' 'Riyadh' 'Doha' 'Mumbai' 'Delhi' 'Bengaluru'
 'Kolkata' 'Chennai' 'Tokyo' 'Osaka' 'Seoul' 'Beijing' 'Shanghai'
 'Hong Kong' 'Singapore' 'Bangkok' 'Kuala Lumpur' 'Jakarta' 'Sydney'
 'Melbourne' 'Auckland' 'Moscow' 'Istanbul' 'Tehran' 'Karachi' 'Manila'
 'Ho Chi Minh City' 'San Francisco' 'Chicago' 'Houston' 'Vancouver'
 'Warsaw' 'Stockholm' 'Helsinki' 'Zurich'] 50

In [53]:
data[["city", "aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]